//+------------------------------------------------------------------+
//|                                           Distance_Dashboard.mq4 |
//|                                                Generated by AI   |
//|                       实时显示距离前两个波段高低点的距离 (基于 ZigZag) |
//+------------------------------------------------------------------+
#property copyright "K-Target User"
#property strict
#property indicator_chart_window

// --- 输入参数 (需与您的 ZigZag 设置一致) ---
input int    InpZigZagDepth     = 12; // ZigZag Depth
input int    InpZigZagDeviation = 5;  // ZigZag Deviation
input int    InpZigZagBackstep  = 3;  // ZigZag Backstep
input int    InpCorner          = CORNER_RIGHT_UPPER; // 面板位置 (默认右上角)
input color  InpTextColor       = clrWhite; // 文字颜色
input int    InpFontSize        = 10;       // 字体大小

// --- 全局变量 ---
string Prefix = "DistDash_";

//+------------------------------------------------------------------+
//| 初始化函数
//+------------------------------------------------------------------+
int OnInit()
{
   // 创建显示对象
   CreateLabel("Title", "=== 结构距离监控 ===", 20, 0, clrBlack);
   CreateLabel("H1", "", 40, 0, clrRed);   // 高点用红色
   CreateLabel("H2", "", 60, 0, clrRed);
   CreateLabel("L1", "", 80, 0, clrBlue);  // 低点用绿色 (或Lime)
   CreateLabel("L2", "", 100, 0, clrBlue);
   
   return(INIT_SUCCEEDED);
}

//+------------------------------------------------------------------+
//| 卸载函数 (清理对象)
//+------------------------------------------------------------------+
void OnDeinit(const int reason)
{
   ObjectsDeleteAll(0, Prefix);
}

//+------------------------------------------------------------------+
//| 主计算函数
//+------------------------------------------------------------------+
int OnCalculate(const int rates_total,
                const int prev_calculated,
                const datetime &time[],
                const double &open[],
                const double &high[],
                const double &low[],
                const double &close[],
                const long &tick_volume[],
                const long &volume[],
                const int &spread[])
{
   // --- 1. 寻找最近的 2 个高点 (H1, H2) ---
   double h1_price = 0, h2_price = 0;
   int found_count = 0;
   
   // 扫描 ZigZag 的 Buffer 1 (存储高点)
   for(int i = 0; i < rates_total; i++)
   {
      // 调用 ZigZag 指标获取第 1 号缓冲区 (High Buffer)
      double val = iCustom(NULL, 0, "ZigZag", InpZigZagDepth, InpZigZagDeviation, InpZigZagBackstep, 1, i);
      
      if(val != 0 && val != EMPTY_VALUE)
      {
         if(found_count == 0) h1_price = val;
         if(found_count == 1) h2_price = val;
         
         found_count++;
         if(found_count >= 2) break; // 找到两个就停止
      }
   }
   
   // --- 2. 寻找最近的 2 个低点 (L1, L2) ---
   double l1_price = 0, l2_price = 0;
   found_count = 0;
   
   // 扫描 ZigZag 的 Buffer 2 (存储低点)
   for(int i = 0; i < rates_total; i++)
   {
      // 调用 ZigZag 指标获取第 2 号缓冲区 (Low Buffer)
      double val = iCustom(NULL, 0, "ZigZag", InpZigZagDepth, InpZigZagDeviation, InpZigZagBackstep, 2, i);
      
      if(val != 0 && val != EMPTY_VALUE)
      {
         if(found_count == 0) l1_price = val;
         if(found_count == 1) l2_price = val;
         
         found_count++;
         if(found_count >= 2) break;
      }
   }
   
   // --- 3. 计算距离并更新面板 ---
   double current_price = Close[0]; // 使用当前收盘价或 Bid
   
   UpdateLabel("H1", "前高 (H1): " + DoubleToString(h1_price, Digits) + " | 距离: " + CalcDist(current_price, h1_price));
   UpdateLabel("H2", "前前高(H2): " + DoubleToString(h2_price, Digits) + " | 距离: " + CalcDist(current_price, h2_price));
   UpdateLabel("L1", "前低 (L1): " + DoubleToString(l1_price, Digits) + " | 距离: " + CalcDist(current_price, l1_price));
   UpdateLabel("L2", "前前低(L2): " + DoubleToString(l2_price, Digits) + " | 距离: " + CalcDist(current_price, l2_price));
   
   return(rates_total);
}

//+------------------------------------------------------------------+
//| 辅助：计算距离字符串
//+------------------------------------------------------------------+
string CalcDist(double current, double target)
{
   if(target == 0) return "N/A";
   double dist = MathAbs(current - target) / Point;
   return IntegerToString((int)dist) + " pts";
}

//+------------------------------------------------------------------+
//| 辅助：创建标签
//+------------------------------------------------------------------+
void CreateLabel(string name, string text, int y_dist, int x_dist, color clr)
{
   string obj_name = Prefix + name;
   if(ObjectFind(0, obj_name) < 0)
      ObjectCreate(0, obj_name, OBJ_LABEL, 0, 0, 0);
      
   ObjectSetInteger(0, obj_name, OBJPROP_CORNER, InpCorner);
   ObjectSetInteger(0, obj_name, OBJPROP_XDISTANCE, x_dist + 300); // 留点边距
   ObjectSetInteger(0, obj_name, OBJPROP_YDISTANCE, y_dist);
   ObjectSetInteger(0, obj_name, OBJPROP_COLOR, clr);
   ObjectSetInteger(0, obj_name, OBJPROP_FONTSIZE, InpFontSize);
   ObjectSetString(0, obj_name, OBJPROP_FONT, "Microsoft YaHei"); // 微软雅黑更清晰
   ObjectSetString(0, obj_name, OBJPROP_TEXT, text);
}

//+------------------------------------------------------------------+
//| 辅助：更新标签内容
//+------------------------------------------------------------------+
void UpdateLabel(string name, string text)
{
   ObjectSetString(0, Prefix + name, OBJPROP_TEXT, text);
}