//+------------------------------------------------------------------+
//|                                           KT_Chart_Navigator.mq4 |
//|                                                Generated by AI   |
//|                                     快速切换已打开的图表窗口     |
//+------------------------------------------------------------------+
#property copyright "K-Target User"
#property strict
#property indicator_chart_window

// --- 参数设置 ---
input int    BtnWidth = 80;        // 按钮宽度
input int    BtnHeight = 20;       // 按钮高度
input int    FontSize = 9;         // 字体大小
input color  BtnBgColor = clrGray; // 按钮背景色
input color  BtnTxtColor= clrWhite;// 按钮文字色
input int    X_Offset = 100;        // 距离右边距
input int    Y_Offset = 20;        // 距离顶边距

string Prefix = "KT_Nav_";

//+------------------------------------------------------------------+
//| 初始化
//+------------------------------------------------------------------+
int OnInit()
{
   DrawButtons();
   return(INIT_SUCCEEDED);
}

//+------------------------------------------------------------------+
//| 卸载
//+------------------------------------------------------------------+
void OnDeinit(const int reason)
{
   ObjectsDeleteAll(0, Prefix);
}

//+------------------------------------------------------------------+
//| 主计算 (只需要响应事件，不需要计算K线)
//+------------------------------------------------------------------+
int OnCalculate(const int rates_total,
                const int prev_calculated,
                const datetime &time[],
                const double &open[],
                const double &high[],
                const double &low[],
                const double &close[],
                const long &tick_volume[],
                const long &volume[],
                const int &spread[])
{
   // 每次有新Tick或者是图表变动时，重新检查一下按钮列表
   // 为了性能，可以加一个简单的限流，这里简化处理直接重绘
   // 实际使用建议只在检测到图表数量变化时重绘
   static int lastChartCount = 0;
   if(GetChartCount() != lastChartCount)
   {
      DrawButtons();
      lastChartCount = GetChartCount();
   }
   return(rates_total);
}

//+------------------------------------------------------------------+
//| 图表事件监听 (点击按钮)
//+------------------------------------------------------------------+
void OnChartEvent(const int id, const long &lparam, const double &dparam, const string &sparam)
{
   if(id == CHARTEVENT_OBJECT_CLICK)
   {
      // 检查是否点击了我们的导航按钮
      if(StringFind(sparam, Prefix) >= 0)
      {
         // 按钮名称格式: KT_Nav_12345678 (后缀是图表ID)
         string id_str = StringSubstr(sparam, StringLen(Prefix));
         long target_chart_id = StringToInteger(id_str);
         
         // 核心功能：将目标图表置顶
         if(target_chart_id > 0)
         {
            ChartSetInteger(target_chart_id, CHART_BRING_TO_TOP, true);
            // 按钮点击动画效果
            ObjectSetInteger(0, sparam, OBJPROP_STATE, false); 
            ChartRedraw();
         }
      }
   }
}

//+------------------------------------------------------------------+
//| 核心：遍历所有图表并画按钮
//+------------------------------------------------------------------+
void DrawButtons()
{
   ObjectsDeleteAll(0, Prefix);
   
   long currChart = ChartFirst();
   int i = 0;
   
   while(i < 100) // 防止死循环，限制最多显示100个
   {
      // 获取图表信息
      string symbol = ChartSymbol(currChart);
      int period = ChartPeriod(currChart);
      string period_str = GetPeriodName(period);
      string label = symbol + " " + period_str;
      
      // 创建按钮
      string btnName = Prefix + IntegerToString(currChart); // ID藏在名字里
      
      if(ObjectFind(0, btnName) < 0)
         ObjectCreate(0, btnName, OBJ_BUTTON, 0, 0, 0);
      
      // 设置按钮属性 (右上角排列)
      ObjectSetInteger(0, btnName, OBJPROP_CORNER, CORNER_RIGHT_UPPER);
      ObjectSetInteger(0, btnName, OBJPROP_XDISTANCE, X_Offset);
      ObjectSetInteger(0, btnName, OBJPROP_YDISTANCE, Y_Offset + (i * (BtnHeight + 2))); // 垂直排列
      ObjectSetInteger(0, btnName, OBJPROP_XSIZE, BtnWidth);
      ObjectSetInteger(0, btnName, OBJPROP_YSIZE, BtnHeight);
      
      ObjectSetString(0, btnName, OBJPROP_TEXT, label);
      ObjectSetString(0, btnName, OBJPROP_FONT, "Arial");
      ObjectSetInteger(0, btnName, OBJPROP_FONTSIZE, FontSize);
      ObjectSetInteger(0, btnName, OBJPROP_BGCOLOR, BtnBgColor);
      ObjectSetInteger(0, btnName, OBJPROP_COLOR, BtnTxtColor);
      ObjectSetInteger(0, btnName, OBJPROP_ZORDER, 10);
      
      // 高亮当前图表的按钮
      if(currChart == ChartID())
      {
         ObjectSetInteger(0, btnName, OBJPROP_BGCOLOR, clrRed); // 当前图表显示红色
      }

      // 获取下一个图表
      currChart = ChartNext(currChart);
      if(currChart < 0) break; // 没有更多图表了
      i++;
   }
   ChartRedraw();
}

//+------------------------------------------------------------------+
//| 辅助：获取图表数量
//+------------------------------------------------------------------+
int GetChartCount()
{
   long curr = ChartFirst();
   int count = 0;
   while(curr >= 0) { count++; curr = ChartNext(curr); }
   return count;
}

//+------------------------------------------------------------------+
//| 辅助：周期转字符串
//+------------------------------------------------------------------+
string GetPeriodName(int p)
{
   switch(p)
   {
      case 1: return "M1";
      case 5: return "M5";
      case 15: return "M15";
      case 30: return "M30";
      case 60: return "H1";
      case 240: return "H4";
      case 1440: return "D1";
      case 10080: return "W1";
      case 43200: return "MN";
   }
   return "";
}