//+------------------------------------------------------------------+
//|                                     Distance_Dashboard_Fixed.mq4 |
//|                                                Generated by AI   |
//|             修正版：基于 ZigZag 最终连线 (Buffer 0) 识别结构距离      |
//+------------------------------------------------------------------+
#property copyright "K-Target User"
#property strict
#property indicator_chart_window

// --- 输入参数 ---
input int    InpZigZagDepth     = 12; // ZigZag Depth
input int    InpZigZagDeviation = 5;  // ZigZag Deviation
input int    InpZigZagBackstep  = 3;  // ZigZag Backstep
input int    InpCorner          = CORNER_RIGHT_UPPER; // 面板位置
input color  InpTextColor       = clrWhite; 
input int    InpFontSize        = 10;       

// --- 全局变量 ---
string Prefix = "DistDash_";

//+------------------------------------------------------------------+
//| 初始化
//+------------------------------------------------------------------+
int OnInit()
{
   CreateLabel("Title", "=== 结构距离监控 (修正版) ===", 20, 0, clrBlack);
   CreateLabel("H1", "扫描中...", 40, 0, clrRed);   
   CreateLabel("H2", "", 60, 0, clrRed);
   CreateLabel("L1", "扫描中...", 80, 0, clrBlue);  
   CreateLabel("L2", "", 100, 0, clrBlue);
   
   return(INIT_SUCCEEDED);
}

//+------------------------------------------------------------------+
//| 卸载
//+------------------------------------------------------------------+
void OnDeinit(const int reason)
{
   ObjectsDeleteAll(0, Prefix);
}

//+------------------------------------------------------------------+
//| 主计算函数
//+------------------------------------------------------------------+
int OnCalculate(const int rates_total,
                const int prev_calculated,
                const datetime &time[],
                const double &open[],
                const double &high[],
                const double &low[],
                const double &close[],
                const long &tick_volume[],
                const long &volume[],
                const int &spread[])
{
   // 存储找到的高低点
   double h1=0, h2=0, l1=0, l2=0;
   int h_count=0, l_count=0;
   
   // 从当前 K 线往前扫描 (i=0 是最新)
   // 我们扫描 Buffer 0 (ExtZigzagBuffer)，这是最终的连线数据
   for(int i = 0; i < rates_total; i++)
   {
      // ✅ 修正点：只读取 Buffer 0 (最终连线)
      double zig_val = iCustom(NULL, 0, "ZigZag", InpZigZagDepth, InpZigZagDeviation, InpZigZagBackstep, 0, i);
      
      // 如果有值 (ZigZag 拐点)
      if(zig_val != 0 && zig_val != EMPTY_VALUE)
      {
         // 判断是高点还是低点
         bool is_high = false;
         bool is_low  = false;
         
         // 获取该 K 线的最高最低价
         // 注意：使用 iHigh/iLow 确保获取的是准确的历史数据
         double bar_high = iHigh(NULL, 0, i);
         double bar_low  = iLow(NULL, 0, i);
         
         // 判定逻辑：
         // 如果 ZigZag 值接近 K 线最高价 -> 高点
         if(MathAbs(zig_val - bar_high) < Point) is_high = true;
         
         // 如果 ZigZag 值接近 K 线最低价 -> 低点
         if(MathAbs(zig_val - bar_low) < Point) is_low = true;
         
         // --- 填充数据 ---
         if(is_high)
         {
            if(h_count == 0) h1 = zig_val;
            else if(h_count == 1) h2 = zig_val;
            h_count++;
         }
         
         if(is_low)
         {
            if(l_count == 0) l1 = zig_val;
            else if(l_count == 1) l2 = zig_val;
            l_count++;
         }
         
         // 如果找齐了 H2 和 L2，提前退出循环，节省性能
         if(h_count >= 2 && l_count >= 2) break;
      }
   }
   
   // --- 更新面板 ---
   double current_price = Close[0];
   
   UpdateLabel("H1", FormatText("前高 (H1)", h1, current_price));
   UpdateLabel("H2", FormatText("前前高(H2)", h2, current_price));
   UpdateLabel("L1", FormatText("前低 (L1)", l1, current_price));
   UpdateLabel("L2", FormatText("前前低(L2)", l2, current_price));
   
   return(rates_total);
}

//+------------------------------------------------------------------+
//| 辅助：格式化显示文本
//+------------------------------------------------------------------+
string FormatText(string title, double price, double current)
{
   if(price == 0) return title + ": 未找到";
   
   int dist_point = (int)(MathAbs(current - price) / Point);
   return title + ": " + DoubleToString(price, Digits) + " | 距离: " + IntegerToString(dist_point) + " pts";
}

//+------------------------------------------------------------------+
//| 辅助：创建标签
//+------------------------------------------------------------------+
void CreateLabel(string name, string text, int y_dist, int x_dist, color clr)
{
   string obj_name = Prefix + name;
   if(ObjectFind(0, obj_name) < 0)
      ObjectCreate(0, obj_name, OBJ_LABEL, 0, 0, 0);
      
   ObjectSetInteger(0, obj_name, OBJPROP_CORNER, InpCorner);
   ObjectSetInteger(0, obj_name, OBJPROP_XDISTANCE, x_dist + 300);
   ObjectSetInteger(0, obj_name, OBJPROP_YDISTANCE, y_dist);
   ObjectSetInteger(0, obj_name, OBJPROP_COLOR, clr);
   ObjectSetInteger(0, obj_name, OBJPROP_FONTSIZE, InpFontSize);
   ObjectSetString(0, obj_name, OBJPROP_FONT, "Microsoft YaHei");
   ObjectSetString(0, obj_name, OBJPROP_TEXT, text);
}

//+------------------------------------------------------------------+
//| 辅助：更新标签内容
//+------------------------------------------------------------------+
void UpdateLabel(string name, string text)
{
   ObjectSetString(0, Prefix + name, OBJPROP_TEXT, text);
}