//+------------------------------------------------------------------+
//|                                     KT_Simple_Breakout_Line.mq4  |
//|                                                Generated by AI   |
//|                   功能：最简破位识别 + 破位价水平线标记            |
//+------------------------------------------------------------------+
#property copyright "K-Target User"
#property strict
#property indicator_chart_window
#property indicator_buffers 2
#property indicator_color1  clrBlue
#property indicator_color2  clrRed

// --- 输入参数 ---
input bool InpShowBullish = true;  // 显示多头破位
input bool InpShowBearish = true;  // 显示空头破位
input int  InpArrowDist   = 15;    // 箭头距离
input bool InpDrawLine    = true;  // [新增] 是否画水平线

// --- 缓冲区 ---
double BullBuffer[];
double BearBuffer[];

// --- 全局变量 ---
string Prefix = "KT_BO_"; // 对象名称前缀

//+------------------------------------------------------------------+
//| 初始化
//+------------------------------------------------------------------+
int OnInit()
{
   SetIndexBuffer(0, BullBuffer);
   SetIndexBuffer(1, BearBuffer);
   
   SetIndexStyle(0, DRAW_ARROW); SetIndexArrow(0, 233);
   SetIndexStyle(1, DRAW_ARROW); SetIndexArrow(1, 234);
   
   SetIndexEmptyValue(0, 0.0);
   SetIndexEmptyValue(1, 0.0);
   
   return(INIT_SUCCEEDED);
}

//+------------------------------------------------------------------+
//| 卸载 (清理线条)
//+------------------------------------------------------------------+
void OnDeinit(const int reason)
{
   ObjectsDeleteAll(0, Prefix);
}

//+------------------------------------------------------------------+
//| 主计算
//+------------------------------------------------------------------+
int OnCalculate(const int rates_total,
                const int prev_calculated,
                const datetime &time[],
                const double &open[],
                const double &high[],
                const double &low[],
                const double &close[],
                const long &tick_volume[],
                const long &volume[],
                const int &spread[])
{
   // [关键] 设置数组为序列方向 (0为最新)，确保逻辑统一
   ArraySetAsSeries(open, true);
   ArraySetAsSeries(close, true);
   ArraySetAsSeries(high, true);
   ArraySetAsSeries(low, true);
   ArraySetAsSeries(time, true);

   int limit = rates_total - prev_calculated;
   if (prev_calculated == 0) limit = rates_total - 2;
   
   for (int i = limit; i >= 0; i--)
   {
      if (i >= rates_total - 1) continue;
      
      BullBuffer[i] = 0.0;
      BearBuffer[i] = 0.0;
      
      double curr_open  = open[i];
      double curr_close = close[i];
      double prev_open  = open[i+1];
      double prev_close = close[i+1];
      
      // [A] 多头破位 (前阴后阳，收盘 > 前开盘)
      if (InpShowBullish)
      {
         bool prev_is_bear = (prev_close < prev_open);
         bool curr_is_bull = (curr_close > curr_open);
         
         if (prev_is_bear && curr_is_bull && curr_close > prev_open)
         {
            BullBuffer[i] = low[i] - InpArrowDist * Point;
            // 画线：传入当前索引 i，价格为前一根开盘价 prev_open
            if(InpDrawLine) DrawLine(i, prev_open, clrBlue, time);
         }
      }
      
      // [B] 空头破位 (前阳后阴，收盘 < 前开盘)
      if (InpShowBearish)
      {
         bool prev_is_bull = (prev_close > prev_open);
         bool curr_is_bear = (curr_close < curr_open);
         
         if (prev_is_bull && curr_is_bear && curr_close < prev_open)
         {
            BearBuffer[i] = high[i] + InpArrowDist * Point;
            if(InpDrawLine) DrawLine(i, prev_open, clrRed, time);
         }
      }
   }
   return(rates_total);
}

//+------------------------------------------------------------------+
//| [新增] 辅助函数：画水平短线
//+------------------------------------------------------------------+
void DrawLine(int idx, double price, color clr, const datetime &time[])
{
   // 使用时间戳作为唯一ID，防止重复创建
   string name = Prefix + IntegerToString((long)time[idx]);
   
   if(ObjectFind(0, name) < 0)
   {
      // 起点：前一根K线时间 (time[idx+1])
      // 终点：当前时间 + 5根K线的时间跨度
      datetime t1 = time[idx+1];
      datetime t2 = time[idx] + PeriodSeconds() * 5; 
      
      ObjectCreate(0, name, OBJ_TREND, 0, t1, price, t2, price);
      ObjectSetInteger(0, name, OBJPROP_COLOR, clr);
      ObjectSetInteger(0, name, OBJPROP_RAY_RIGHT, false); // 不射线，只画短线
      ObjectSetInteger(0, name, OBJPROP_WIDTH, 2);
      ObjectSetInteger(0, name, OBJPROP_STYLE, STYLE_SOLID);
      ObjectSetInteger(0, name, OBJPROP_SELECTABLE, false);
   }
}