//+------------------------------------------------------------------+
//|                                           Close_All_Orders.mq4   |
//|                                                Generated by AI   |
//|                          一键清空所有订单 (平仓 + 删挂单)            |
//+------------------------------------------------------------------+
#property copyright "K-Target User"
#property link      "https://www.mql5.com"
#property version   "1.00"
#property strict
#property show_inputs // 运行时弹出参数窗口，防止误触

// --- 输入参数 ---
input string __WARNING__           = "=== ⚠️ 警告：此操作不可逆 ===";
input bool   Only_Current_Symbol   = false;  // 只关闭当前图表品种? (false=清空全账户)
input bool   Delete_Pending_Orders = true;   // 是否同时删除挂单?
input int    Target_Magic_Number   = 0;      // 只关闭特定魔术号 (0=不限制，全部关闭)
input int    Slippage              = 20;     // 允许滑点 (微点)
input int    Retry_Count           = 3;      // 失败重试次数

//+------------------------------------------------------------------+
//| 脚本主程序
//+------------------------------------------------------------------+
void OnStart()
{
   int total = OrdersTotal();
   if(total == 0) 
   {
      Alert("当前账户没有订单。");
      return;
   }

   int count_closed = 0;
   int count_deleted = 0;
   int count_failed = 0;

   // ⚠️ 核心逻辑：必须从后往前遍历 (倒序)，因为平仓会改变订单总数和索引
   for(int i = total - 1; i >= 0; i--)
   {
      // 1. 选中订单
      if(!OrderSelect(i, SELECT_BY_POS, MODE_TRADES)) continue;

      // 2. 过滤条件
      // 如果开启了"只关当前品种"，且订单品种不符，跳过
      if(Only_Current_Symbol && OrderSymbol() != Symbol()) continue;
      
      // 如果指定了魔术号，且订单魔术号不符，跳过
      if(Target_Magic_Number != 0 && OrderMagicNumber() != Target_Magic_Number) continue;

      // 3. 执行操作
      bool result = false;
      int type = OrderType();
      int ticket = OrderTicket();
      double lot = OrderLots();
      string symbol = OrderSymbol();
      
      // --- 处理持仓单 (OP_BUY / OP_SELL) ---
      if(type == OP_BUY || type == OP_SELL)
      {
         // 获取平仓价格
         double close_price = (type == OP_BUY) ? MarketInfo(symbol, MODE_BID) : MarketInfo(symbol, MODE_ASK);
         
         // 尝试平仓 (带重试机制)
         for(int k=0; k<Retry_Count; k++)
         {
            RefreshRates(); // 刷新价格
            close_price = (type == OP_BUY) ? MarketInfo(symbol, MODE_BID) : MarketInfo(symbol, MODE_ASK);
            
            result = OrderClose(ticket, lot, close_price, Slippage, clrYellow);
            if(result) 
            {
               count_closed++;
               break; // 成功则跳出重试
            }
            else
            {
               Print("平仓失败 Ticket:", ticket, " Error:", GetLastError(), " 重试中...");
               Sleep(100); // 等待100毫秒再试
            }
         }
      }
      // --- 处理挂单 (OP_BUYLIMIT 等) ---
      else if(Delete_Pending_Orders)
      {
         result = OrderDelete(ticket, clrGray);
         if(result) count_deleted++;
         else Print("删单失败 Ticket:", ticket, " Error:", GetLastError());
      }
      
      if(!result) count_failed++;
   }

   // 4. 结果反馈
   string msg = "执行完毕!\n";
   if(count_closed > 0) msg += "已平仓: " + IntegerToString(count_closed) + "\n";
   if(count_deleted > 0) msg += "已删单: " + IntegerToString(count_deleted) + "\n";
   if(count_failed > 0) msg += " 失败: " + IntegerToString(count_failed);
   
   if(count_closed > 0 || count_deleted > 0) 
      Alert(msg);
   else if (count_failed > 0)
      Alert("操作遇到错误，请查看专家日志。");
}