//+------------------------------------------------------------------+
//|                                          Delete_Trade_Arrows.mq4 |
//|                                                Generated by AI   |
//|                          精准删除名称以 # 开头的交易订单箭头          |
//+------------------------------------------------------------------+
#property copyright "K-Target User"
#property link      "https://www.mql5.com"
#property version   "1.00"
#property strict
#property show_inputs // 允许弹出参数窗口(虽然本脚本没参数，但保留是个好习惯)

//+------------------------------------------------------------------+
//| 脚本主程序
//+------------------------------------------------------------------+
void OnStart()
{
   int total_objects = ObjectsTotal(0, -1, -1); // 获取主图表所有对象
   int deleted_count = 0;
   
   // ⚠️ 必须从后往前遍历，因为删除对象会改变索引
   for(int i = total_objects - 1; i >= 0; i--)
   {
      string obj_name = ObjectName(0, i);
      
      // --- 核心匹配逻辑 ---
      
      // 1. 特征一：名称必须以 '#' 开头 (MT4 订单箭头的铁律)
      // StringFind 返回 0 表示在字符串起始位置找到
      if(StringFind(obj_name, "#") == 0)
      {
         // === 新增功能：删除订单轨迹画线 ===
         // 特征：类型为趋势线 + 名称包含 "->" 模式
         // 示例：#40265328 5213.68 -> 5213.13
         int obj_type = ObjectType(obj_name);
         if(obj_type == OBJ_TREND && StringFind(obj_name, " -> ") != -1)
         {
            if(ObjectDelete(0, obj_name))
            {
               deleted_count++;
            }
            continue;  // 已处理，跳到下一个对象
         }
         
         // 2. 特征二：名称中包含 "buy"、"sell" 或 "modified" (双重确认，防止误删自定义的 # 标签)
         // StringToLower 将名称转为小写，忽略大小写差异
         string name_lower = obj_name;
         StringToLower(name_lower);
         
         if(StringFind(name_lower, " buy ") != -1 || 
            StringFind(name_lower, " sell ") != -1 || 
            StringFind(name_lower, "modified") != -1)
         {
            // 3. 执行删除
            if(ObjectDelete(0, obj_name))
            {
               deleted_count++;
            }
         }
         // 特殊情况：如果您想删除所有 # 开头的对象，
         // 可以把上面的 if(StringFind...) 注释掉，
         // 只保留 if(StringFind(obj_name, "#") == 0) 这一层判断。
      }
   }
   
   // 打印结果到“专家”选项卡
   Print("════════════════════════════════════════════");
   Print(" 交易标记清理完成！");
   Print("────────────────────────────────────────────");
   Print(" 共删除: ", deleted_count, " 个对象");
   Print("   └─ 包含订单轨迹线和交易箭头");
   Print("════════════════════════════════════════════");
   // Comment("已清理 ", deleted_count, " 个交易箭头。");
   // Sleep(1000);
   // Comment(""); // 清除注释
}
//+------------------------------------------------------------------+