//+------------------------------------------------------------------+
//|                                          Delete_Trade_Arrows.mq4 |
//|                                                Generated by AI   |
//|                          精准删除名称以 # 开头的交易订单箭头          |
//+------------------------------------------------------------------+
#property copyright "K-Target User"
#property link      "https://www.mql5.com"
#property version   "1.00"
#property strict
#property show_inputs // 允许弹出参数窗口(虽然本脚本没参数，但保留是个好习惯)

//+------------------------------------------------------------------+
//| 脚本主程序
//+------------------------------------------------------------------+
void OnStart()
{
   int total_objects = ObjectsTotal(0, -1, -1); // 获取主图表所有对象
   int deleted_count = 0;
   
   // ⚠️ 必须从后往前遍历，因为删除对象会改变索引
   for(int i = total_objects - 1; i >= 0; i--)
   {
      string obj_name = ObjectName(0, i);
      
      // --- 核心匹配逻辑 ---
      
      // 1. 特征一：名称必须以 '#' 开头 (MT4 订单箭头的铁律)
      // StringFind 返回 0 表示在字符串起始位置找到
      if(StringFind(obj_name, "#") == 0)
      {
         // 2. 特征二：名称中通常包含 "buy" 或 "sell" (双重确认，防止误删自定义的 # 标签)
         // StringToLower 将名称转为小写，忽略大小写差异
         string name_lower = obj_name;
         StringToLower(name_lower);
         
         if(StringFind(name_lower, " buy ") != -1 || StringFind(name_lower, " sell ") != -1)
         {
            // 3. 执行删除
            if(ObjectDelete(0, obj_name))
            {
               deleted_count++;
            }
         }
         // 特殊情况：如果是限价单(Limit/Stop)可能包含其他关键词，
         // 如果您只想删除所有 # 开头的，可以把上面的 if(StringFind...) 注释掉，
         // 只保留 if(StringFind(obj_name, "#") == 0) 这一层判断。
      }
   }
   
   // 打印结果到“专家”选项卡
   Print(" 清理完成！共删除了 ", deleted_count, " 个交易箭头对象。");
   // Comment("已清理 ", deleted_count, " 个交易箭头。");
   // Sleep(1000);
   // Comment(""); // 清除注释
}
//+------------------------------------------------------------------+